name: ColorChat
main: com.minecraft.moonlakedev.colorchat.ColorChatPlugin
version: 1.0.3
author: Month_Light
website: http://www.mcyszh.com
depend: [DeluxeChat]
commands:
  colorchat:
  clearcolor:
  randomcolor:
